/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthLayoutImport } from './routes/auth/layout'
import { Route as IndexImport } from './routes/index'
import { Route as PollIdIndexImport } from './routes/$pollId/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as PollIdResultImport } from './routes/$pollId/result'
import { Route as PollIdCreateNewVoteImport } from './routes/$pollId/create-new-vote'

// Create/Update Routes

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PollIdIndexRoute = PollIdIndexImport.update({
  id: '/$pollId/',
  path: '/$pollId/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const PollIdResultRoute = PollIdResultImport.update({
  id: '/$pollId/result',
  path: '/$pollId/result',
  getParentRoute: () => rootRoute,
} as any)

const PollIdCreateNewVoteRoute = PollIdCreateNewVoteImport.update({
  id: '/$pollId/create-new-vote',
  path: '/$pollId/create-new-vote',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/$pollId/create-new-vote': {
      id: '/$pollId/create-new-vote'
      path: '/$pollId/create-new-vote'
      fullPath: '/$pollId/create-new-vote'
      preLoaderRoute: typeof PollIdCreateNewVoteImport
      parentRoute: typeof rootRoute
    }
    '/$pollId/result': {
      id: '/$pollId/result'
      path: '/$pollId/result'
      fullPath: '/$pollId/result'
      preLoaderRoute: typeof PollIdResultImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthLayoutImport
    }
    '/$pollId/': {
      id: '/$pollId/'
      path: '/$pollId'
      fullPath: '/$pollId'
      preLoaderRoute: typeof PollIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/$pollId/create-new-vote': typeof PollIdCreateNewVoteRoute
  '/$pollId/result': typeof PollIdResultRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$pollId': typeof PollIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/$pollId/create-new-vote': typeof PollIdCreateNewVoteRoute
  '/$pollId/result': typeof PollIdResultRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$pollId': typeof PollIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/$pollId/create-new-vote': typeof PollIdCreateNewVoteRoute
  '/$pollId/result': typeof PollIdResultRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$pollId/': typeof PollIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/$pollId/create-new-vote'
    | '/$pollId/result'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$pollId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$pollId/create-new-vote'
    | '/$pollId/result'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$pollId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/$pollId/create-new-vote'
    | '/$pollId/result'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$pollId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  PollIdCreateNewVoteRoute: typeof PollIdCreateNewVoteRoute
  PollIdResultRoute: typeof PollIdResultRoute
  PollIdIndexRoute: typeof PollIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PollIdCreateNewVoteRoute: PollIdCreateNewVoteRoute,
  PollIdResultRoute: PollIdResultRoute,
  PollIdIndexRoute: PollIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/$pollId/create-new-vote",
        "/$pollId/result",
        "/$pollId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/layout.tsx",
      "children": [
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/$pollId/create-new-vote": {
      "filePath": "$pollId/create-new-vote.tsx"
    },
    "/$pollId/result": {
      "filePath": "$pollId/result.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx",
      "parent": "/auth"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx",
      "parent": "/auth"
    },
    "/$pollId/": {
      "filePath": "$pollId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
